name: update-readme

on:
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  updateTetrio:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
    
      - name: Get region rank position
        run: |
          API_URL="https://ch.tetr.io/api/users/araponga/summaries/league"
          STANDING_LOCAL_VALUE=$(curl -s "$API_URL" | jq -r '.data.standing_local')

          if [ -z "$STANDING_LOCAL_VALUE" ] || [ "$STANDING_LOCAL_VALUE" == "null" ]; then
            echo "Error extracting 'standing_local' from the API or null value. URL: $API_URL"
            exit 1
            
          else
            echo "Standing Local extracted: $STANDING_LOCAL_VALUE"
            
            sed -i -E "s/#([0-9]+)/#${rank}/" README.md
          fi

      - name: Commit changes
        run: |
          git config --local user.email "viniciuslsilveira.1201@gmail.com"
          git config --local user.name "GitHub Action"

          if ! git diff --quiet README.md; then
            git add README.md
            git commit -m "Update TETR.IO stats"
            echo "Changes to README.md commited"
            git push
          else
            echo "Nothing to commit, same rank $STANDING_LOCAL_VALUE"
          fi
